/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_playh264_jni_Decoder */

#ifndef _Included_com_android_playh264_jni_Decoder
#define _Included_com_android_playh264_jni_Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_playh264_jni_Decoder
 * Method:    InitDecoder
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_android_playh264_jni_Decoder_InitDecoder
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_android_playh264_jni_Decoder
 * Method:    UninitDecoder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_playh264_jni_Decoder_UninitDecoder
  (JNIEnv *, jobject);

/*
 * Class:     com_android_playh264_jni_Decoder
 * Method:    DecoderNal
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_android_playh264_jni_Decoder_DecoderNal
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
